---
title: "presidential_speeches"
author: "Owen Bernstein"
date: "4/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Loading necessary packages

library(gt)
library(broom)
library(skimr)
library(lubridate)
library(janitor)
library(dotwhisker)
library(tidytext)
library(ggthemes)
library(webshot)
library(tidyverse)
```

```{r data loading, include = FALSE}

# Reading in the data and then using bind rows to combine the candidates'
# speeches.

clinton_speeches <- read_csv("raw-data/hilary_clinton_speeches.csv")
trump_speeches <- read_csv("raw-data/donald_trump_speeches.csv")
sanders_speeches <- read_csv("raw-data/bernie_sanders_speeches.csv")
romney_speeches <- read_csv("raw-data/mitt_romney_speeches.csv")
obama_speeches <- read_csv("raw-data/barack_obama_speeches.csv")
mccain_speeches <- read_csv("raw-data/john_mccain_speeches.csv")

speeches <- bind_rows(clinton_speeches, trump_speeches,
                      sanders_speeches, romney_speeches,
                      obama_speeches, mccain_speeches)

# Cleaning the speeches and counting the number of words while removing stop
# words.

tidy_speeches <- speeches %>% 
  select("Speaker":"Text") %>% 
  clean_names() %>% 
  filter(speaker == "Donald Trump" | speaker == "Hilary Clinton" |
           speaker == "Bernie Sanders" | speaker == "Mitt Romney" |
           speaker == "Barack Obama" | speaker == "John McCain") %>% 
  group_by(speaker, title, region, date) %>% 
  unnest_tokens(word, text) %>%
  anti_join(stop_words) %>% 
  filter(! word %in% c("applause", "inaudible","cheers", "laughing",
                       "[applause]", "[inaudible]", "[cheers]",
                       "[laughing]", "(applause)", "(inaudible)","(cheers)",
                       "(laughing)")) %>% 
  count(word) %>% 
  mutate(total_words = sum(n))
```

```{r basket of words, include = FALSE}

# Counting words by each differnet content category

populism <- tidy_speeches %>% 
  group_by(speaker, title, region, total_words, date) %>% 
  filter(str_detect(word, "deceit") | str_detect(word, "treason")
         | str_detect(word, "betray") | str_detect(word, "absurd")
         | str_detect(word, "arrogant") | str_detect(word, "promise") 
         | str_detect(word, "corrupt") | str_detect(word, "direct")
         | str_detect(word, "elite") | str_detect(word, "establishment")
         | str_detect(word, "ruling") | str_detect(word, "caste")
         | str_detect(word, "class") | str_detect(word, "mafia")
         | str_detect(word, "freedom of expression")
         | str_detect(word, "undemocratic") | str_detect(word, "politic")
         | str_detect(word, "propaganda") | str_detect(word, "referend")
         | str_detect(word, "regime") | str_detect(word, "shame")
         | str_detect(word, "admit") | str_detect(word, "tradition")
         | str_detect(word, "people")) %>% 
  mutate(populism_count = sum(n)) %>% 
  arrange(desc(populism_count))

environment <- tidy_speeches %>% 
  group_by(speaker, title, region, total_words, date) %>% 
  filter(str_detect(word, "green") | str_detect(word, "climate")
         | str_detect(word, "environment") | str_detect(word, "heating")
         | str_detect(word, "durable")) %>% 
  mutate(environment_count = sum(n)) %>% 
  arrange(desc(environment_count))

immigration <- tidy_speeches %>% 
  group_by(speaker, title, region, total_words, date) %>% 
  filter(str_detect(word, "asylum") | str_detect(word, "halal")
         | str_detect(word, "scarf") | str_detect(word, "illegal")
         | str_detect(word, "immigra") | str_detect(word, "Islam") 
         | str_detect(word, "Koran") | str_detect(word, "Muslim")
         | str_detect(word, "foreign")) %>% 
  mutate(immigration_count = sum(n)) %>% 
  arrange(desc(immigration_count))

progressive <- tidy_speeches %>% 
  group_by(speaker, title, region, total_words, date) %>% 
  filter(str_detect(word,"progress") | str_detect(word, "right")
         | str_detect(word, "freedom") | str_detect(word, "self-disposition")
         | str_detect(word, "handicap") | str_detect(word, "poverty") 
         | str_detect(word, "protection") | str_detect(word, "honest")
         | str_detect(word, "equal") | str_detect(word, "education")
         | str_detect(word, "pension") | str_detect(word, "social") 
         | str_detect(word, "weak")) %>% 
  mutate(progressive_count = sum(n)) %>% 
  arrange(desc(progressive_count))

conservatism <- tidy_speeches %>% 
  group_by(speaker, title, region, total_words, date) %>% 
  filter(str_detect(word, "belief") | str_detect(word, "famil")
         | str_detect(word, "church") | str_detect(word, "norm")
         | str_detect(word, "porn") | str_detect(word, "sex")
         | str_detect(word, "values") | str_detect(word, "conservative")
         | str_detect(word, "conservatism") | str_detect(word, "custom")) %>% 
  mutate(conservatism_count = sum(n)) %>% 
  arrange(desc(conservatism_count))

# Combining each of the conent categories into a single data frame. Also adding
# party affiliations and percent values

sentiment_speeches <- populism %>% 
  full_join(environment, by = c("title", "date", "speaker", "region",
                                "total_words")) %>% 
  full_join(immigration, by = c("title", "date", "speaker", "region",
                                "total_words")) %>% 
  full_join(progressive, by = c("title", "date", "speaker", "region",
                                "total_words")) %>% 
  full_join(conservatism, by = c("title", "date", "speaker", "region",
                                 "total_words"))%>%
  select(speaker, region, total_words, date, title, populism_count,
         environment_count, immigration_count, 
         progressive_count, conservatism_count) %>%
  ungroup() %>% 
  mutate(populism_percent = populism_count / total_words * 100,
         environment_percent = environment_count / total_words * 100,
         immigration_percent = immigration_count / total_words * 100,
         progressive_percent = progressive_count / total_words * 100,
         conservatism_percent = conservatism_count / total_words * 100,
         party = ifelse(speaker == "Donald Trump" |
                          speaker == "Mitt Romney" |
                          speaker == "John McCain", "Republican", "Democrat"),
         date = mdy(date)) %>%
  distinct()
```

```{r bar charts, include = FALSE}

# Setting nas to 0

sentiment_speeches[is.na(sentiment_speeches)] = 0

# Creating bar charts by candidate for each content category

populism_hist <- sentiment_speeches %>% 
  ggplot(aes(populism_percent)) +
  geom_histogram(bins = 10) +
  facet_wrap(~ speaker) +
  labs(title = "Populist Language in Speeches by Candidate",
       x = "Percent Populist Language",
       y = "Number of Speeches") +
  theme_minimal()

populism_hist

ggsave("presidential_speeches/pop_hist_plot.png")

immigration_hist <- sentiment_speeches %>% 
  ggplot(aes(immigration_percent)) +
  geom_histogram(bins = 10) +
  facet_wrap(~ speaker) +
  labs(title = "Language Relating to Immigration in Speeches by Candidate",
       x = "Percent Language Relating to Immigration",
       y = "Number of Speeches") +
  theme_minimal()

immigration_hist

ggsave("presidential_speeches/img_hist_plot.png")

environment_hist <- sentiment_speeches %>% 
  ggplot(aes(environment_percent)) +
  geom_histogram(bins = 10) +
  facet_wrap(~ speaker) +
  labs(title = "Language Relating to the Envrironment in Speeches by Candidate",
       x = "Percent Language Relating to the Environment",
       y = "Number of Speeches") +
  theme_minimal()

environment_hist

ggsave("presidential_speeches/env_hist_plot.png")

progressive_hist <- sentiment_speeches %>% 
  ggplot(aes(progressive_percent)) +
  geom_histogram(bins = 10) +
  facet_wrap(~ speaker) +
  labs(title = "Progressive Language in Speeches by Candidate",
       x = "Percent Progressive Language",
       y = "Number of Speeches") +
  theme_minimal()

progressive_hist

ggsave("presidential_speeches/pro_hist_plot.png")

conservatism_hist <- sentiment_speeches %>% 
  ggplot(aes(conservatism_percent)) +
  geom_histogram(bins = 10) +
  facet_wrap(~ speaker) +
  labs(title = "Conservative Language in Speeches by Candidate",
       x = "Percent Conservative Language",
       y = "Number of Speeches") +
  theme_minimal()

conservatism_hist

ggsave("presidential_speeches/con_hist_plot.png")
```

```{r box plots, include = FALSE}

# Setting nas to 0

sentiment_speeches[is.na(sentiment_speeches)] = 0

# Creating box plots for each candidate by category

populism_box <- sentiment_speeches %>% 
  ggplot(., aes(speaker, populism_percent)) +
  geom_boxplot() + 
  labs(title = "Populist Language in Speeches by Candidate",
       x = "Candidate", y = "Percent Populist Language") +
  theme_minimal() +
  theme(axis.line = element_line())

populism_box

ggsave("presidential_speeches/pop_box_plot.png")

immigration__box <- ggplot(sentiment_speeches, aes(speaker, immigration_percent)) +
  geom_boxplot() +
  labs(title = "Language Relating to Immigration in Speeches by Candidate",
       x = "Candidate", y = "Percent
       Language Relating to Immigration") +
  theme_minimal() +
  theme(axis.line = element_line())

immigration__box

ggsave("presidential_speeches/img_box_plot.png")

environment_box <- ggplot(sentiment_speeches,
                          aes(speaker, environment_percent)) +
  geom_boxplot() +
  labs(title = "Language Relating to the Environment in Speeches by Candidate",
       x = "Candidate", y = "Percent Populist Language") +
  theme_minimal() +
  theme(axis.line = element_line())

environment_box

ggsave("presidential_speeches/env_box_plot.png")

progressive_box <- ggplot(sentiment_speeches,
                          aes(speaker, progressive_percent)) +
  geom_boxplot() +
  labs(title = "Progressive Language in Speeches by Candidate",
       x = "Candidate", y = "Percent Progressive Language") +
  theme_minimal() +
  theme(axis.line = element_line())

progressive_box

ggsave("presidential_speeches/pro_box_plot.png")

conservatism_box <- ggplot(sentiment_speeches,
                           aes(speaker, conservatism_percent)) +
  geom_boxplot() +
  labs(title = "Conservative Language in Speeches by Candidate",
       x = "Candidate", y = "Percent Conservative Language") +
  theme_minimal() +
  theme(axis.line = element_line())

conservatism_box 

ggsave("presidential_speeches/con_box_plot.png")
```

```{r linear regression, include = FALSE}

# Setting nas to 0

sentiment_speeches[is.na(sentiment_speeches)] = 0

# Making linear regression plots for each candidate by category

populism_regression <- lm(populism_percent ~ speaker, sentiment_speeches)

pop_reg <- dwplot(populism_regression, show_intercept = T,
                  conf.level = .95) %>%
  relabel_predictors("(Intercept)" = "Barack Obama as Baseline",
                     "speakerBernie Sanders" = "Bernie Sanders",
                     "speakerDonald Trump" = "Donald Trump",
                     "speakerHilary Clinton" = "Hilary Clinton",
                     "speakerMitt Romney" = "Mitt Romney",
                     "speakerJohn McCain" = "John McCain") +
  theme_minimal() +
  theme(legend.position = "none") +
  geom_vline(xintercept = 0, colour = "grey60", linetype = 2) +
  labs(title = "Linear Regression of Candidate on Percent
       Populist Language",
       x = "Coefficient Estimate")

pop_reg

ggsave("presidential_speeches/pop_reg_plot.png")

immigration_regression <- lm(immigration_percent ~ speaker, sentiment_speeches)

img_reg <- dwplot(immigration_regression, show_intercept = T,
                  conf.level = .95) %>%
  relabel_predictors("(Intercept)" = "Barack Obama as Baseline",
                     "speakerBernie Sanders" = "Bernie Sanders",
                     "speakerDonald Trump" = "Donald Trump",
                     "speakerHilary Clinton" = "Hilary Clinton",
                     "speakerMitt Romney" = "Mitt Romney",
                     "speakerJohn McCain" = "John McCain") +
  theme_minimal() +
  theme(legend.position = "none") +
  geom_vline(xintercept = 0, colour = "grey60", linetype = 2) +
  labs(title = "Linear Regression of Candidate on Percent Language
       Relating to Immigration",
       x = "Coefficient Estimate")

img_reg

ggsave("presidential_speeches/img_reg_plot.png")

environment_regression <- lm(environment_percent ~ speaker, sentiment_speeches)

env_reg <- dwplot(environment_regression, show_intercept = T,
                  conf.level = .95) %>%
  relabel_predictors("(Intercept)" = "Barack Obama as Baseline",
                     "speakerBernie Sanders" = "Bernie Sanders",
                     "speakerDonald Trump" = "Donald Trump",
                     "speakerHilary Clinton" = "Hilary Clinton",
                     "speakerMitt Romney" = "Mitt Romney",
                     "speakerJohn McCain" = "John McCain") +
  theme_minimal() +
  theme(legend.position = "none") +
  geom_vline(xintercept = 0, colour = "grey60", linetype = 2) +
  labs(title = "Linear Regression of Candidate on Percent Language
       Relating to the Environment",
       x = "Coefficient Estimate")

env_reg

ggsave("presidential_speeches/env_reg_plot.png")

progressive_regression <- lm(progressive_percent ~ speaker, sentiment_speeches)

pro_reg <- dwplot(progressive_regression, show_intercept = T,
                  conf.level = .95) %>%
  relabel_predictors("(Intercept)" = "Barack Obama as Baseline",
                     "speakerBernie Sanders" = "Bernie Sanders",
                     "speakerDonald Trump" = "Donald Trump",
                     "speakerHilary Clinton" = "Hilary Clinton",
                     "speakerMitt Romney" = "Mitt Romney",
                     "speakerJohn McCain" = "John McCain") +
  theme_minimal() +
  theme(legend.position = "none") +
  geom_vline(xintercept = 0, colour = "grey60", linetype = 2) +
  labs(title = "Linear Regression of Candidate on Percent
       Progressive Language",
       x = "Coefficient Estimate")

pro_reg

ggsave("presidential_speeches/pro_reg_plot.png")

conservatism_regression <- lm(conservatism_percent ~ speaker,
                              sentiment_speeches)

con_reg <- dwplot(conservatism_regression, show_intercept = T,
                  conf.level = .95) %>%
  relabel_predictors("(Intercept)" = "Barack Obama as Baseline",
                     "speakerBernie Sanders" = "Bernie Sanders",
                     "speakerDonald Trump" = "Donald Trump",
                     "speakerHilary Clinton" = "Hilary Clinton",
                     "speakerMitt Romney" = "Mitt Romney",
                     "speakerJohn McCain" = "John McCain") +
  theme_minimal() +
  theme(legend.position = "none") +
  geom_vline(xintercept = 0, colour = "grey60", linetype = 2) +
  labs(title = "Linear Regression of Candidate on Percent
       Conservative Language",
       x = "Coefficient Estimate")

con_reg

ggsave("presidential_speeches/con_reg_plot.png")
```

```{r}

# Making histograms for each category by party

sentiment_speeches[is.na(sentiment_speeches)] = 0

party_populism_hist <- sentiment_speeches %>% 
  ggplot(aes(populism_percent)) +
  geom_histogram(bins = 10) +
  facet_wrap(~ party) +
  labs(title = "Populist Language in Speeches by Party",
       x = "Percent Populist Language",
       y = "Number of Speeches") +
  theme_minimal()

party_populism_hist

ggsave("presidential_speeches/party_pop_hist_plot.png")


party_immigration_hist <- sentiment_speeches %>% 
  ggplot(aes(immigration_percent)) +
  geom_histogram(bins = 10) +
  facet_wrap(~ party) +
  labs(title = "Language Relating to Immigration in Speeches by Party",
       x = "Percent Language Relating to Immigration",
       y = "Number of Speeches") +
  theme_minimal()

party_immigration_hist

ggsave("presidential_speeches/party_img_hist_plot.png")

party_environment_hist <- sentiment_speeches %>% 
  ggplot(aes(environment_percent)) +
  geom_histogram(bins = 10) +
  facet_wrap(~ party) +
  labs(title = "Language Relating to the Envrironment in Speeches by party",
       x = "Percent Language Relating to the Environment",
       y = "Number of Speeches") +
  theme_minimal()

party_environment_hist

ggsave("presidential_speeches/party_env_hist_plot.png")

party_progressive_hist <- sentiment_speeches %>% 
  ggplot(aes(progressive_percent)) +
  geom_histogram(bins = 10) +
  facet_wrap(~ party) +
  labs(title = "Progressive Language in Speeches by Party",
       x = "Percent Progressive Language",
       y = "Number of Speeches") +
  theme_minimal()

party_progressive_hist

ggsave("presidential_speeches/party_pro_hist_plot.png")

party_conservatism_hist <- sentiment_speeches %>% 
  ggplot(aes(conservatism_percent)) +
  geom_histogram(bins = 10) +
  facet_wrap(~ party) +
  labs(title = "Conservative Language in Speeches by Party",
       x = "Percent Conservative Language",
       y = "Number of Speeches") +
  theme_minimal()

party_conservatism_hist

ggsave("presidential_speeches/party_con_hist_plot.png")
```

```{r}

# Setting nas to 0

sentiment_speeches[is.na(sentiment_speeches)] = 0

# Creating box plots for each party by category

party_populism_box <- sentiment_speeches %>% 
  ggplot(., aes(party, populism_percent)) +
  geom_boxplot() + 
  labs(title = "Populist Language in Speeches by Party",
       x = "Party", y = "Percent Populist Language") +
  theme_minimal() +
  theme(axis.line = element_line())

party_populism_box

ggsave("presidential_speeches/party_pop_box_plot.png")

party_immigration__box <- ggplot(sentiment_speeches, aes(party,
                                                         immigration_percent)) +
  geom_boxplot() +
  labs(title = "Language Relating to Immigration in Speeches by Party",
       x = "Party", y = "Percent
       Language Relating to Immigration") +
  theme_minimal() +
  theme(axis.line = element_line())

party_immigration__box

ggsave("presidential_speeches/party_img_box_plot.png")

party_environment_box <- ggplot(sentiment_speeches,
                          aes(party, environment_percent)) +
  geom_boxplot() +
  labs(title = "Language Relating to the Environment in Speeches by Party",
       x = "Party", y = "Percent Populist Language") +
  theme_minimal() +
  theme(axis.line = element_line())

party_environment_box

ggsave("presidential_speeches/party_env_box_plot.png")

party_progressive_box <- ggplot(sentiment_speeches,
                          aes(party, progressive_percent)) +
  geom_boxplot() +
  labs(title = "Progressive Language in Speeches by Party",
       x = "Party", y = "Percent Progressive Language") +
  theme_minimal() +
  theme(axis.line = element_line())

party_progressive_box

ggsave("presidential_speeches/party_pro_box_plot.png")

party_conservatism_box <- ggplot(sentiment_speeches,
                           aes(party, conservatism_percent)) +
  geom_boxplot() +
  labs(title = "Conservative Language in Speeches by Party",
       x = "Party", y = "Percent Conservative Language") +
  theme_minimal() +
  theme(axis.line = element_line())

party_conservatism_box 

ggsave("presidential_speeches/party_con_box_plot.png")
```

```{r}

sentiment_speeches[is.na(sentiment_speeches)] = 0

pop_time <- ggplot(sentiment_speeches, aes(date, populism_percent)) +
  geom_jitter(alpha = 0.5, width = 100) +
  geom_smooth(method = "lm", se = F) +
  labs(title = "Populist Language in Presidential Speeches Over Time",
       x = "Date of Speech", y = "Percent Populist Language") +
  theme_minimal()

populism_time


img_time <- ggplot(sentiment_speeches, aes(date, immigration_percent)) +
  geom_jitter(alpha = 0.5, width = 100) +
  geom_smooth(method = "lm", se = F) +
  labs(title = "Language Relating to Immigration in Presidential Speeches Over Time",
       x = "Date of Speech", y = "Percent Language Relating to Immigration") +
  theme_minimal()

img_time

env_time <- ggplot(sentiment_speeches, aes(date, environment_percent)) +
  geom_jitter(alpha = 0.5, width = 100) +
  geom_smooth(method = "lm", se = F) +
  labs(title = "Language Relating to the Environment in Presidential Speeches Over Time",
       x = "Date of Speech", y = "Percent Language Relating to the Environment") +
  theme_minimal()

env_time

pro_time <- ggplot(sentiment_speeches, aes(date, progressive_percent)) +
  geom_jitter(alpha = 0.5, width = 100) +
  geom_smooth(method = "lm", se = F) +
  labs(title = "Progressive Language in Presidential Speeches Over Time",
       x = "Date of Speech", y = "Percent Progressive Language") +
  theme_minimal()

pro_time

con_time <- ggplot(sentiment_speeches, aes(date, conservatism_percent)) +
  geom_jitter(alpha = 0.5, width = 100) +
  geom_smooth(method = "lm", se = F) +
  labs(title = "Conservative Language in Presidential Speeches Over Time",
       x = "Date of Speech", y = "Percent Conservative Language") +
  theme_minimal()

con_time
```

```{r}

lm(populism_percent ~ date, data = sentiment_speeches) %>% 
  tidy(conf.int = T)


```








